//@version=6
// @author LazyBear 
// List of all my indicators: https://www.tradingview.com/v/4IneGo8h/
//

strategy(shorttitle = 'SQZMOM_LB', title = 'Squeeze Momentum Indicator [LazyBear]', overlay = false, process_orders_on_close = true)

length = input(20, title = 'BB Length')
mult = input(2.0, title = 'BB MultFactor')
lengthKC = input(20, title = 'KC Length')
multKC = input(1.5, title = 'KC MultFactor')

useTrueRange = input(true, title = 'Use TrueRange (KC)')

// Calculate BB
source = close
basis = ta.sma(source, length)
dev = multKC * ta.stdev(source, length)
upperBB = basis + dev
lowerBB = basis - dev

// Calculate KC
ma = ta.sma(source, lengthKC)
range_1 = useTrueRange ? ta.tr : high - low
rangema = ta.sma(range_1, lengthKC)
upperKC = ma + rangema * multKC
lowerKC = ma - rangema * multKC

sqzOn = lowerBB > lowerKC and upperBB < upperKC
sqzOff = lowerBB < lowerKC and upperBB > upperKC
noSqz = sqzOn == false and sqzOff == false

val = ta.linreg(source - math.avg(math.avg(ta.highest(high, lengthKC), ta.lowest(low, lengthKC)), ta.sma(close, lengthKC)), lengthKC, 0)

iff_1 = val > nz(val[1]) ? color.lime : color.green // long 진입 모멘텀
iff_2 = val < nz(val[1]) ? color.red : color.maroon // short 진입 모멘텀
bcolor = val > 0 ? iff_1 : iff_2
scolor = noSqz ? color.blue : sqzOn ? color.black : color.gray

cond1 = (not noSqz) and (not sqzOn) // true: 변동성 큼, false: 변동성 작음
cond2 = val > 0 // true: long, false: short

check1 = cond1 ? 1 : 0
check2 = cond2 ? 1 : 0
isVolaStart = ta.change(check1) == 1
isMomentumChange = ta.change(check2) != 0
isLong = isVolaStart and cond2
isShort = isVolaStart and not cond2

if isLong
    strategy.entry("롱", strategy.long)
    if strategy.position_size == 0
        strategy.exit("롱", stop = close * 0.99, limit = close * 1.01)
if isMomentumChange
    strategy.close("롱")

// if isShort
//     strategy.entry("숏", strategy.short)
// if isMomentumChange
//     strategy.close("숏")

plot(val, color = bcolor, style = plot.style_histogram, linewidth = 4)
plot(0, color = scolor, style = plot.style_cross, linewidth = 2)
