// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © adolgov

// @description
// 

//@version=6
strategy('Stop loss and Take Profit', overlay = true)

// random entry condition

longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if longCondition
    strategy.entry('My Long Entry Id', strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if shortCondition
    strategy.entry('My Short Entry Id', strategy.short)

moneyToSLPoints(money) =>
    strategy.position_size != 0 ? money / syminfo.pointvalue / math.abs(strategy.position_size) / syminfo.mintick : na

p = moneyToSLPoints(input(200, title = 'Take Profit $$'))
l = moneyToSLPoints(input(100, title = 'Stop Loss $$'))
strategy.exit('x', profit = p, loss = l)

// debug plots for visualize SL & TP levels
pointsToPrice(pp) =>
    na(pp) ? na : strategy.position_avg_price + pp * math.sign(strategy.position_size) * syminfo.mintick

pp = plot(pointsToPrice(p), style = plot.style_linebr)
lp = plot(pointsToPrice(-l), style = plot.style_linebr)
avg = plot(strategy.position_avg_price, style = plot.style_linebr)
fill(pp, avg, color = color.new(color.green, 90))
fill(avg, lp, color = color.new(color.red, 90))
